import React, { ReactNode } from 'react';
import { notFound } from 'next/navigation';
import { Metadata } from 'next';
import 'primereact/resources/themes/lara-light-cyan/theme.css';
import AuthProvider from '../../AuthProvider';

import '@style';
import { NextIntlClientProvider } from 'next-intl';
import { FlexHeader, Footer } from '@components';
import ToastProvider from './ToastProvider';

export const metadata: Metadata = {
  title: 'Services Center',
  description: 'Generated by create next app',
};
type Props = {
  children: ReactNode;
  params: { locale: string; path?: string };
};
export default async function RootLayout(props: Props) {
  const { params, children } = props;

  let messages;
  try {
    messages = (await import(`../../../messages/${params.locale}.json`)).default;
  } catch (error) {}

  if (!messages) return notFound();
  return (
    <html
      lang={params.locale}
      dir={params.locale === 'en' ? 'ltr' : 'rtl'}
      data-layout-dir={params.locale === 'en' ? 'ltr' : 'rtl'}
      data-preloader="disable"
    >
      <body dir={params.locale === 'en' ? 'ltr' : 'rtl'}>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <AuthProvider>
            <FlexHeader />
            <ToastProvider locale={params.locale as 'en' | 'ar'} />

            {children}
            <footer>
              <Footer />
            </footer>
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
